services: 
  todo-app:
    image: getting_started:0.2
    ports: 
      - 2345:3000
    working_dir: /app
    environment:
      MYSQL_HOST: mysql-todo-app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: todo_database
    volumes:
      - ./:/etc/todos
  mysql-todo-app:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_database

volumes:
  mysql: